# Terraform configuration generated by "/Users/tgreco/agoric-sdk/packages/deployment/bin/ag-setup-cosmos init"

variable "NETWORK_NAME" {
  default = "deployment"
}

variable "SSH_KEY_FILE" {
  default = "id_ecdsa.pub"
}

variable "DATACENTERS" {
  default = {"docker1"=["default","default"],"docker2"=["default","default","default"],"docker3"=["default","default","default","default"]}
}

variable "OFFSETS" {
  default = {"docker1"=0,"docker2"=0,"docker3"=0}
}

variable "ROLES" {
  default = {"docker1"="validator","docker2"="peer","docker3"="seed"}
}

variable "VOLUMES" {
  default = {"docker1"=[],"docker2"=[],"docker3"=[]}
}

